# Model arguments
model_name_or_path: model_cache/phi-3.5-mini-instruct
torch_dtype: null
use_peft: true
trust_remote_code: true
use_flash_attention_2: true

bf16: true
do_eval: true
evaluation_strategy: steps
eval_steps: 250
gradient_accumulation_steps: 1
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: microsoft/Phi-3.5-mini-instruct
learning_rate: 2.0e-5
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
num_train_epochs: 5
optim: adamw_torch
lora_alpha: 4
# lora_target_modules: [qkv_proj, o_proj,gate_up_proj,down_proj]
lora_target_modules: [qkv_proj, o_proj]
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "steps"
save_steps: 500
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
report_to: wandb
remove_unused_columns: false