# Model arguments
model_name_or_path: model_cache/llama3-8b
model_name_for_short: llama3-8b
torch_dtype: null
use_peft: true
trust_remote_code: true
use_flash_attention_2: true

bf16: true
do_eval: true
evaluation_strategy: steps
eval_steps: 250
gradient_accumulation_steps: 2
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: False
save_only_model: true
hub_model_id: meta-llama/Meta-Llama-3-8B
learning_rate: 2.0e-5
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
num_train_epochs: 3
optim: adamw_torch
lora_r: 64
lora_alpha: 128
# lora_alpha: 4
# lora_r: 16
# lora_target_modules: [qkv_proj, o_proj,gate_up_proj,down_proj]
lora_target_modules: [q_proj, k_proj, v_proj, o_proj]
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
push_to_hub: false
save_strategy: "steps"
save_steps: 500
save_total_limit: 4
seed: 42
warmup_ratio: 0.1
report_to: wandb
remove_unused_columns: false

output_dir: ckpt/instruct_lm/llama3